### ISSUE TITLE
npm run causes errors and doesn't start

### ISSUE THREAD

**Issue by Divinely5782** [jdempcy/hdkit#5]
Hi! Thank you so much for your effort in open source Human Design software. I cloned your repo, installed all dependencies than when i tried to run your commands from package.json - each of them has encountered errors and didnt run. Both for hdblacklist and pdf generator. Maybe you can make a preview with https://stackblitz.com to show if its working? Thanks!

**Comment by Divinely5782** [comment]
For example hdblacklist-client: i do `npm run start` and then in terminal:
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\hdkit\sample-apps\hdblacklist-client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\hdkit\sample-apps\hdblacklist-client\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\hdkit\sample-apps\hdblacklist-client\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\hdkit\sample-apps\hdblacklist-client\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\hdkit\sample-apps\hdblacklist-client\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\hdkit\sample-apps\hdblacklist-client\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\hdkit\sample-apps\hdblacklist-client\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (D:\hdkit\sample-apps\hdblacklist-client\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
D:\hdkit\sample-apps\hdblacklist-client\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\hdkit\sample-apps\hdblacklist-client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\hdkit\sample-apps\hdblacklist-client\node_modules\webpack\lib\NormalModule.js:417:16)    
    at D:\hdkit\sample-apps\hdblacklist-client\node_modules\webpack\lib\NormalModule.js:452:10
    at D:\hdkit\sample-apps\hdblacklist-client\node_modules\webpack\lib\NormalModule.js:323:13
    at D:\hdkit\sample-apps\hdblacklist-client\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\hdkit\sample-apps\hdblacklist-client\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\hdkit\sample-apps\hdblacklist-client\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\hdkit\sample-apps\hdblacklist-client\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0

**Comment by tutucea** [comment]
i can confirm the same error using ubuntu  btw  
```
abel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.13.0
```

**Comment by RedRosh** [comment]
you can fix the   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ] by adding `--openssl-legacy-provider` in package.json
```
    "start": "craco --openssl-legacy-provider  start",
```
